server:
  port: 9000
kafka:
  topic: test
  consumerGroupId: group_id
  server: localhost:9092
  concurrency:
      level: 5
  consumer:
      enabled: true
  producer:
      enabled: false
  ssl:
      endpoint:
           identification:
               mechanism:
  sasl:
      jaas:
           config:
               username: admin
               password: admin                  
  
  security:
      enabled: false
  
#  producerPackagename: abcd